name: PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db_testing
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    timeout-minutes: 30

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
          tools: composer:v2

      - uses: actions/checkout@v3

      - name: Setup environment
        run: php -r "file_exists('.env.testing') || copy('.env.testing.ci', '.env.testing');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run tests
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: vendor/bin/phpunit --testsuite Unit

      - name: Print log file
        run: cat storage/logs/laravel.log
        if: always()

    feature:
      runs-on: ubuntu-latest

      services:
        mysql:
          image: mysql:8.0.21
          env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: db_testing
          ports:
            - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      timeout-minutes: 30

      steps:
        - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
          with:
            php-version: '8.0'
            tools: composer:v2

        - uses: actions/checkout@v3

        - name: Setup environment
          run: php -r "file_exists('.env.testing') || copy('.env.testing.ci', '.env.testing');"

        - name: Install Dependencies
          run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

        - name: Directory Permissions
          run: chmod -R 777 storage bootstrap/cache

        - name: Run tests
          env:
            DB_PORT: ${{ job.services.mysql.ports[3306] }}
          run: vendor/bin/phpunit --testsuite Feature

        - name: Print log file
          run: cat storage/logs/laravel.log
          if: always()
